version: "3.8"  # docker engine version

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports: 
      - '5432:5432'
    volumes:
      - backend-db:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.development
    environment:
      DB_SCHEMA: "${DB_SCHEMA}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.development
    environment:
      STREAMA_ENDPOINT: "${STREAMA_ENDPOINT}"
      API_ENDPOINT: "${API_ENDPOINT}"
    ports:
      - '8081:8081'

volumes:
  backend-db: