name: CI Workflow

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request targeting main branch

# Define the jobs that will run
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest  # Specifies the Ubuntu runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your repository under $GITHUB_WORKSPACE
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you need
          
      - name: Install dependencies
        run: npm install  # Adjust this command to your project setup

      - name: Run tests
        run: npm test  # Adjust this to your test script
