name: Docker Compose CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on pull request targeting main branch

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Install Docker Compose

      - name: Run Docker Compose Up
        run: docker-compose up # Run docker-compose in detached mode
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          STREAMA_ENDPOINT: ${{ secrets.STREAMA_ENDPOINT }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          ADMIN_SECRETS: ${{ secrets.ADMIN_SECRETS }}
          SUPERUSER_SECRETS: ${{ secrets.SUPERUSER_SECRETS }}
          DB_SCHEMA: ${{ vars.DB_SCHEMA }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}

      - name: Wait for services to be healthy
        run: |
          docker-compose ps
          # Optionally add commands to check service health if required

      - name: Clean up Docker Compose
        run: docker-compose down # Stop and remove containers
